version: 2


models:
  - name: stg_events
    description: This table has information about events.
    
    columns:
      - name: event_id
        description: This is the unique identifier of an event. (Primary Key)
        tests:
          - unique
          - not_null
      - name: group_id
        description: The unique identifier of the group that organised this event.
      - name: name
        description: The title of the event.
      - name: description
        description: The description of the event.
      - name: created_at
        description: Timestamp of the moment the event was created by the organiser.
      - name: start_time
        description: The timestamp of when the event will start (or has started).
      - name: duration_seconds
        description: The duration of the event, in seconds.
      - name: rsvp_limit
        description: The maximum number of YES RSVPs that this event will allow.
      - name: venue_id
        description: Unique identifier of the venue where this event takes place (see below).
      - name: status
        description: The status of the event. Possible values include 'past' and 'upcoming', meaning the the event has already taken place or that the event is planned for the future respectively.
      - name: rsvps
        description: An array of RSVP objects, which contain the following fields; user_id, when, response, guests


  - name: stg_events_responses
    description: This table has information about user responses to events.
    
    columns:
      - name: event_id
        description: This is the unique identifier of an event.
      - name: user_id
        description: The unique identifier of the user that RSVPed for this event.
      - name: responded_at
        description: Timestamp of the moment the user gave their RSVP.
      - name: response
        description: Yes or No or Waitlist (Yes), the indication of whether this user will attend the event.
      - name: guests
        description: If permitted, the number of guests that the user is planning to bring to the event.
      - name: rsvp_limit
        description: The maximum number of YES RSVPs that this event will allow.
  

  - name: stg_groups
    description: This table has information about groups.
    
    columns:
      - name: group_id
        description: This is the unique identifier of a group. (Primary Key)
        tests:
          - unique
          - not_null
      - name: name
        description: Name of the group.
      - name: description
        description: Description of the group.
      - name: link
        description: Link to the group's homepage.
      - name: created_at
        description: Timestamp of when the group was created.
      - name: city
        description: Name of the city where the group resides.
      - name: lat
        description: Latitude of the place where the group resides.
      - name: lon
        description: Longitude of the place where the group resides.
      - name: topics
        description: Array of topics that this group discusses or otherwise associates with.


  - name: stg_groups_topics
    description: This table has information about group topics.
    
    columns:
      - name: group_id
        description: This is the unique identifier of a group.
      - name: topics
        description: An array of topics unnested into rows from stg_groups.topics field, belonging to the group_id. 


  - name: stg_users
    description: This table has information about users.
    
    columns:
      - name: user_id
        description: This is the unique identifier for a user. (Primary Key)
        tests:
          - unique
          - not_null
      - name: country
        description: Country where the user resides.
      - name: city
        description: City where the user resides.
      - name: hometown
        description: Town that the user specified as their home town.
      - name: memberships
        description:  Array of membership objects, containing the following fields; joined, group_id


  - name: stg_users_memberships
    description: This table has information about users' memberships.
    
    columns:
      - name: user_id
        description: This is the unique identifier for a user.
      - name: group_id
        description: This is the unique identifier of the group that the user has joined.
      - name: joined_at
        description: Timestamp of the moment the user joined this group.


  - name: stg_venues
    description: This table has information about venues.
    
    columns:
      - name: venue_id
        description: This is the unique identifier for a venue. (Primary Key)
        tests:
          - unique
          - not_null
      - name: name
        description: The name of the venue.
      - name: city
        description: The city where the venue is located.
      - name: country
        description: The country where the venue is located.
      - name: lat
        description: The lattitude of the venue location.
      - name: lon
        description: The longitude of the venue location.
        