version: 2


models:
  - name: stg_events
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    
    columns:
      - name: event_id
        description: This is the unique identifier of an event.
        tests:
          - unique
          - not_null
      - name: group_id
        description: The unique identifier of the group that organised this event.
      - name: name
        description: The title of the event.
      - name: description
        description: The description of the event.
      - name: created_at
        description: Timestamp of the moment the event was created by the organiser.
      - name: start_time
        description: The timestamp of when the event will start (or has started).
      - name: duration_seconds
        description: The duration of the event, in seconds.
      - name: rsvp_limit
        description: The maximum number of YES RSVPs that this event will allow.
      - name: venue_id
        description: Unique identifier of the venue where this event takes place (see below).
      - name: status
        description: The status of the event. Possible values include 'past' and 'upcoming', meaning the the event has already taken place or that the event is planned for the future respectively.
      - name: rsvps
        description: An array of RSVP objects, which contain the following fields; user_id, when, response, guests


  - name: stg_events_responses
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
  

  - name: stg_groups
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 

  - name: stg_groups_topics
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 

  - name: stg_users
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 

  - name: stg_users_memberships
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 

  - name: stg_venues
    description: 
    
    columns:
      - name: 
        description: 
        tests:
          - unique
          - not_null
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
      - name: 
        description: 
        